### ISSUE TITLE
Storing laps

### ISSUE THREAD

**Issue by grezniczek** [davwillev/stopwatch#10]
A very easy to implement way would be to store the laps in a notes field.

Storage as repeat instances of a separate form would require 2 things:
- the configuration logic for the user to set this up, and 
- the logic to actually create these instances.

What exactly should be stored? What is optional? How to configure (for the user who sets up the instruments)?

**Comment by davwillev** [comment]
All good questions, @grezniczek 

**1. What exactly should be stored?**
Time intervals can be captured as [splits or laps](https://news.runtowin.com/2007/05/08/what-is-the-difference-between-split-times-and-lap-times.html); the former would be a direct capture, the latter resets at zero after each capture, so would require a difference. It would be easy for a user to do this manually, but these are nice options if automated.

**2. What is optional?**
Splits/laps (as above).
It would be nice if the user didn't have to specify the (maximum) number of laps or splits in advance. We were saving multiple captures/results in an array, but how we save them in REDCap variables is potentially the tricky bit.

**3. How to configure (for the user who sets up the instruments)?**
From a UI perspective, I alternated a 'capture' button with the 'reset' button. This is nice and simple for capturing time instances (splits). If using a table to display saved splits, we could add a second column for laps (difference from previous split) as an option (display/save either splits, laps or both)? This would potentially lead to lots of variables, but this is up to the user.

**Comment by grezniczek** [comment]
https://github.com/davwillev/stopwatch/tree/beta.7 adds storing of laps / slips (captures), either as JSON or in a repeating form.

Configuration for now is exclusively via a JSON parameter to @STOPWATCH.
