### ISSUE TITLE
HTML IDs

### ISSUE THREAD

**Issue by grezniczek** [davwillev/stopwatch#3]
The generated HTML makes use of IDs, which will lead to problems further down, i.e. can't have two or more stopwatches on the same page, or there may be conflicts with other EMs.

Either ids need to be unique, or (preferred) no ids are used at all.

**Comment by davwillev** [comment]
Thanks for pointing this out, @grezniczek 
I'm not sure how best to implement this by removing IDs completely.
I think there is some code in the stopwatch.js file (lines 234-263, pasted in from the ImageMap EM) that might help us if we want to link IDs to the REDCap question.

**Comment by grezniczek** [comment]
This can be achieved while building the DOM elements and hooking up event handlers there. 
The context will then be the element that triggered the event (from which the row in the data entry / survey can be found; or the event handlers are put on the row itself).

**Comment by davwillev** [comment]
Should this be set out in the stopwatch.js file?

**Comment by grezniczek** [comment]
The dev implementation supports multiple stopwatches per form.
