### ISSUE TITLE
Check docs for spelling and grammar

### ISSUE THREAD

**Issue by grezniczek** [davwillev/stopwatch#31]

**Comment by davwillev** [comment]
I'll have a thorough look through now if you like

**Comment by grezniczek** [comment]
Sure, if you have time.

I was thinking of (offering to be) presenting some modules (My Project Tweaks, External Module Management Tools, and maybe a sneak preview of some others) in the next Friday consortium call. If this happens, then maybe Stopwatch could be briefly shown there, too. This would mean to ideally push a v1.0.0 to the Repo by then.

**Comment by davwillev** [comment]
Great idea! I would love to see this used by REDCappers

I've made some changes for you to review. Please check that I haven't made any errors with regard to content. Thanks!

**Comment by grezniczek** [comment]
Thanks. Great changes! It's much more readable now. Go, native speakers!
