### ISSUE TITLE
Missing data codes?

### ISSUE THREAD

**Issue by grezniczek** [davwillev/stopwatch#4]
How to handle?

**Comment by davwillev** [comment]
We need an equivalent to 'did not start' (DNS), like in running or motorsport races. Maybe the reset function should also reinstate this state?
What's the current convention for missing data in REDCap? I am aware that there is a new Missing Data Codes feature, but not sure if conventions have yet been formed.

**Comment by grezniczek** [comment]
A relatively simple solution would be to check for presence of a MDC and disable (hide) the Stopwatch widget. A prerequisite/limitation would be that the row with the textbox must not be hidden or read only. 
A little more involved would be to duplicated the MDC functionality in the Stopwatch UI.

**Comment by davwillev** [comment]
I think duplicating MDC would be overkill, unless absolutely necessary.
From a UI perspective, are you thinking of adding a 'did not start' (or similar) single checkbox for the user to indicate that they did not need/use the stopwatch after all, which would then hide the widget from view?
If data collection was abandoned before the user got to the stopwatch stage and the field remained empty, would we use the MDC set by the user or default to our own DNS value of MDC was not set?

**Comment by grezniczek** [comment]
Interesting questions ...
I guess it all largely depends how the person designing a form wants to limit (or not limit) the data entry person. Choices are: show the target field at all or not? Allow manual entry?  I guess this is up to the project designer.
If the target field is read-only, then the Stopwatch is the only way to enter data, but this would preclude MDC (unless provided by the Stopwatch). 
Regarding tbe "abandoned" scenario .. I guess the field would just remain empty as it would be otherwise.
Maybe this is something for future refinements when more feedback from actual use comes in.

**Comment by davwillev** [comment]
Thinking about this some more. Data should default to ‘missing’ unless entered by the stopwatch. This would preclude the need to declare a stopwatch as unnecessary, etc. I know you are much further ahead now, but thought I would continue this thread

**Comment by grezniczek** [comment]
I think I found a good way to integrate MDCs, which is implemented in beta.6.
