### ISSUE TITLE
Start with widget at top of display (and keep it there)

### ISSUE THREAD

**Issue by davwillev** [davwillev/stopwatch#44]
When using a text box, the widget begins at the tope of the field display and stays there as rows are added to the capture table. However, when using a Text Box or Notes Box with lots of text, the widget begins in the vertical centre of the field and gradually moves upward as rows are added to the table. This means that the user has to keep looking at the widget to 'chase' the buttons up the display to continue using them. This is potentially distracting to the user and risks missing a button click.
<img width="288" alt="Screenshot 2020-05-29 at 20 10 48" src="https://user-images.githubusercontent.com/35876659/83297271-2c8bcc80-a1ea-11ea-89a6-4c40cfaf7d26.png">

Once the table fills the space, the top of the table reaches the top of the field space (after 10 rows or so) and remains there. As more rows are added, the field display increases in size and rows are now just added to the bottom of the table. This latter behaviour feels correct and is easy to use.

**Comment by grezniczek** [comment]
Laps/capture stopwatches are now vertically aligned at the top of their container by default. This can be changed with the new `at_top` setting. 9ae99a6fd66da9cf0e41e73200d8043d38af2803
