### ISSUE TITLE
Enhance Tab Interaction, and prevent skipping of Stopwatch(es) after openening a data entry form or a survey

### ISSUE THREAD

**Issue by grezniczek** [davwillev/stopwatch#46]

**Comment by grezniczek** [comment]
This could be considered a bug

**Comment by davwillev** [comment]
We are digging deep now. Well spotted!

**Comment by grezniczek** [comment]
https://github.com/davwillev/stopwatch/commit/1fa6f1f235d0cc3ef320e8edbb49ae42f1c76b01 should fix this. 

This should be tested some more, though!
