### ISSUE TITLE
ERROR - calculated fields

### ISSUE THREAD

**Issue by cristobalcar** [davwillev/stopwatch#54]
Hi guys!
When using stopwatch fields into a calculated field, the stopwatch shows an `error.`
<img width="739" alt="image" src="https://user-images.githubusercontent.com/29803674/175384359-8e4e0942-9dd3-4e34-bf17-e503f9870a86.png">

**Comment by grezniczek** [comment]
@cristobalcar , could you add some more information, please?

Best, the (complete) relevant part of the data dictionary, i.e. field type, validation, field annotation (action tag), or an instrument.zip or a project.xml file.

**Comment by cristobalcar** [comment]
We are using events and this is the data dictionary
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/29803674/175391944-fe0e0689-f9f3-44cb-a0ea-9257d2c2396f.png">

**Comment by grezniczek** [comment]
Ah, ok. You cannot use MM:SS validated fields in calculations. Only numbers can be used. Set the type to Integer or Number, and specify the display format (mm:ss) of the stopwatch in the action tag parametrs.

```
@STOPWATCH={
  "digits": 2,
  "show_target": true,
  "display_format": "/m:/s"
}
```

**Comment by cristobalcar** [comment]
Thank you @grezniczek
