### ISSUE TITLE
Can stopwatch track form completion time?

### ISSUE THREAD

**Issue by RaymondBalise** [davwillev/stopwatch#56]
Hello stopwatch folks,
I am looking for a way to track time on task for public facing REDCap surveys.  Can stopwatch be set to start the timer when a survey is shown and stopped when the user submits the form?  If not, can you suggest alternatives to capture time on task?  I would like to try to calculate "typical" completion times?

I am a statistician not a web programmer so clues for the clueless would be greatly appreciated.
Ray

**Comment by grezniczek** [comment]
Hey Ray,
This request has come up several times. My answer always is: No. And there is no real point in measuring survey times anyways, because you cannot rely on the values (survey starts, phone rings, +83 minutes for those two questions).

**BUT:**
I can't remember when exactly this was introduced, but recent versions of REDCap do actually record both survey start and end times:
![image](https://user-images.githubusercontent.com/25482666/222490692-b4efef22-77ef-4cac-acc9-1ed27e8d9e91.png)

Unfortunately, the start time is not yet exported, but there are smart variables giving access to these, such as  
`[survey-duration-completed:instrument:units]`.

Just add this as, e.g., a calc field (or retro-fit forms and run Rule H):
![image](https://user-images.githubusercontent.com/25482666/222492398-eda138c3-e11e-4e65-a57a-aa7b1c505d83.png)

**Comment by RaymondBalise** [comment]
Fabulous.  This is super helpful!  If you make it to Miami, lunch is on me. 😊

Ray

Raymond R. Balise, PhD
Associate  Professor
Department of Public Health Sciences, Biostatistics

University of Miami, Miller School of Medicine
1120 N.W. 14th Street
Don Soffer Clinical Research Center - Room 1061
Miami, Florida 33136

(305) 243-9694

To request help from the Center for HIV and Research in Mental Health (CHARM) please go here<https://redcap.miami.edu/surveys/?s=EEWDYECME7>.  To provide post-consult feedback go here<https://redcap.miami.edu/surveys/?s=EYMEPRMCJP&consultant=1>. Please remember to acknowledge CHARM in your papers if resources were used (P30MH116867).

Confidentiality Notice: This e-mail transmission, and any documents, files or previous e-mail messages attached to it, may contain confidential information. If you are not the intended recipient, or a person responsible for delivering it to the intended recipient, you are hereby notified that any disclosure, copying, distribution or use of any of the information contained in or attached to this message is STRICTLY PROHIBITED. If you have received this transmission in error, please immediately notify us by reply e-mail or by telephone at (305) 243-9694  and destroy the original transmission and its attachments without reading them or saving them to disk.



From: Günther Rezniczek ***@***.***>
Date: Thursday, March 2, 2023 at 11:35 AM
To: davwillev/stopwatch ***@***.***>
Cc: Balise, Raymond R ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [davwillev/stopwatch] Can stopwatch track form completion time? (Issue #56)
CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.

Hey Ray,
This request has come up several times. My answer always is: No. And there is no real point in measuring survey times anyways, because you cannot rely on the values (survey starts, phone rings, +83 minutes for those two questions).

BUT:
I can't remember when exactly this was introduced, but recent versions of REDCap do actually record both survey start and end times:
[image]<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F25482666%2F222490692-b4efef22-77ef-4cac-acc9-1ed27e8d9e91.png&data=05%7C01%7Cbalise%40miami.edu%7C5b219691e28e4ce91ba908db1b3c2720%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C638133717396973724%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NLHfRTLHNBYo8pBtRawkrsBYiDZXQYMaOcrpOPdOHv4%3D&reserved=0>

Unfortunately, the start time is not yet exported, but there are smart variables giving access to these, such as
[survey-duration-completed:instrument:units].

Just add this as, e.g., a calc field (or retro-fit forms and run Rule H):
[image]<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F25482666%2F222492398-eda138c3-e11e-4e65-a57a-aa7b1c505d83.png&data=05%7C01%7Cbalise%40miami.edu%7C5b219691e28e4ce91ba908db1b3c2720%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C638133717396973724%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=h7FPj9TtSemY3QKwgpSLJ7%2ByrgeCLajW13C%2F6TimLy4%3D&reserved=0>

**Comment by grezniczek** [comment]
My pleasure ;)

Oh, and for multiple tasks within a survey ... use 1 page per section and capture the transitions with `@DEFAULT` or `@SETVALUE`. You may have to restrict going back. And as always: Keep in mind that survey timings captured in a non-controlled environment are anything but reliable.

**Comment by RaymondBalise** [comment]
Thank you.  The extra tips are super helpful.

We are running into issues with bots (even with reCAPTCHA).  I am hoping that I can get clues for finding them by spotting super-fast responses on the initial screener.  I have no idea if the bad-actors are smart enough to program response latency… we will soon find out.

Ray

Raymond R. Balise, PhD
Associate  Professor
Department of Public Health Sciences, Biostatistics

University of Miami, Miller School of Medicine
1120 N.W. 14th Street
Don Soffer Clinical Research Center - Room 1061
Miami, Florida 33136

(305) 243-9694

To request help from the Center for HIV and Research in Mental Health (CHARM) please go here<https://redcap.miami.edu/surveys/?s=EEWDYECME7>.  To provide post-consult feedback go here<https://redcap.miami.edu/surveys/?s=EYMEPRMCJP&consultant=1>. Please remember to acknowledge CHARM in your papers if resources were used (P30MH116867).

Confidentiality Notice: This e-mail transmission, and any documents, files or previous e-mail messages attached to it, may contain confidential information. If you are not the intended recipient, or a person responsible for delivering it to the intended recipient, you are hereby notified that any disclosure, copying, distribution or use of any of the information contained in or attached to this message is STRICTLY PROHIBITED. If you have received this transmission in error, please immediately notify us by reply e-mail or by telephone at (305) 243-9694  and destroy the original transmission and its attachments without reading them or saving them to disk.



From: Günther Rezniczek ***@***.***>
Date: Thursday, March 2, 2023 at 11:39 AM
To: davwillev/stopwatch ***@***.***>
Cc: Balise, Raymond R ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [davwillev/stopwatch] Can stopwatch track form completion time? (Issue #56)
CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.

My pleasure ;)

Oh, and for multiple tasks within a survey ... use 1 page per section and capture the transitions with @DEFAULT or @SETVALUE. You may have to restrict going back. And as always: Keep in mind that survey timings captured in a non-controlled environment are anything but reliable.

**Comment by grezniczek** [comment]
You might even add some text to an initial gatekeeper survey, saying something like "If you are a human, please wait for at least X seconds before you click the checkbox and submit" and then use Auto-continue with logic (making use of the duration smart variable). If they don't pass this test, put something like this in the completion text:
_You appear not to be a human. If you are, please read the instructions and try again._

**Comment by grezniczek** [comment]
![image](https://user-images.githubusercontent.com/25482666/222497571-b92bbaf5-4438-4619-bdc4-ad2b34ea42d2.png)

**Comment by RaymondBalise** [comment]
Oh I like that!

Ray

Raymond R. Balise, PhD
Associate  Professor
Department of Public Health Sciences, Biostatistics

University of Miami, Miller School of Medicine
1120 N.W. 14th Street
Don Soffer Clinical Research Center - Room 1061
Miami, Florida 33136

(305) 243-9694

To request help from the Center for HIV and Research in Mental Health (CHARM) please go here<https://redcap.miami.edu/surveys/?s=EEWDYECME7>.  To provide post-consult feedback go here<https://redcap.miami.edu/surveys/?s=EYMEPRMCJP&consultant=1>. Please remember to acknowledge CHARM in your papers if resources were used (P30MH116867).

Confidentiality Notice: This e-mail transmission, and any documents, files or previous e-mail messages attached to it, may contain confidential information. If you are not the intended recipient, or a person responsible for delivering it to the intended recipient, you are hereby notified that any disclosure, copying, distribution or use of any of the information contained in or attached to this message is STRICTLY PROHIBITED. If you have received this transmission in error, please immediately notify us by reply e-mail or by telephone at (305) 243-9694  and destroy the original transmission and its attachments without reading them or saving them to disk.



From: Günther Rezniczek ***@***.***>
Date: Thursday, March 2, 2023 at 11:53 AM
To: davwillev/stopwatch ***@***.***>
Cc: Balise, Raymond R ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [davwillev/stopwatch] Can stopwatch track form completion time? (Issue #56)
CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.

You might even add some text to an initial gatekeeper survey, saying something like "If you are a human, please wait for at least X seconds before you click the checkbox and submit" and then use Auto-continue with logic (making use of the duration smart variable). If they don't pass this test, put something like this in the completion text:
You appear not to be a human. If you are, please read the instructions and try again.
