### ISSUE TITLE
Stopwatch for time_mm_ss should not show hours

### ISSUE THREAD

**Issue by grezniczek** [davwillev/stopwatch#6]

**Comment by davwillev** [comment]
Should the minute count continue beyond 60 here, or do you want to automatically stop at 59.59?

**Comment by grezniczek** [comment]
The REDCap field type only accepts at most 59:59. So a value >= 60 mins cannot be stored in a field with `time_mm_ss` validation.

**Comment by grezniczek** [comment]
Addressed with https://github.com/davwillev/stopwatch/commit/983e83dcebcdfa09ec06f992b5cf9767842f3a83 and https://github.com/davwillev/stopwatch/commit/dfa91f34641d030800d8e7e06f9f88f0b1af55f9
