### ISSUE TITLE
When a field is blank, the Stopwatch should reflect that 

### ISSUE THREAD

**Issue by grezniczek** [davwillev/stopwatch#9]
by dislaying not `0:00:00.000` but maybe `-:--:--.---` or `<blank>` or something like this.

**Comment by davwillev** [comment]
`-:--:--.---` looks best I think

**Comment by grezniczek** [comment]
Addressed with https://github.com/davwillev/stopwatch/commit/dfa91f34641d030800d8e7e06f9f88f0b1af55f9. The symbol used could be exposed as a config setting.
